## Configuração para integração com banco PostgreSQL
#server:
#  port: 8080
#  servlet:
#    context-path: /bootcamp
#
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url:
#    username:
#    password:
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: none
#
#application:
#  description: Projeto criado para o bootcamp DIO - Santander | Backend